[build]
builder = "NIXPACKS"
buildCommand = "npm install --no-optional --ignore-scripts && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE" 